include(GNUInstallDirs)
install(TARGETS mira BUNDLE DESTINATION . RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(WIN32 OR APPLE)
  qt_generate_deploy_qml_app_script(TARGET mira OUTPUT_SCRIPT deploy_script)
  install(SCRIPT ${deploy_script})
endif()
if(UNIX AND NOT APPLE)
  configure_file(packaging/mira.desktop.in generated/${APP_ID}.desktop @ONLY)
  configure_file(packaging/metainfo.xml.in generated/${APP_ID}.metainfo.xml @ONLY)
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/generated/${APP_ID}.desktop DESTINATION share/applications)
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/generated/${APP_ID}.metainfo.xml DESTINATION share/metainfo)
  install(FILES assets/mira.svg DESTINATION share/icons/hicolor/scalable/apps RENAME ${APP_ID}.svg)
endif()
install(FILES LICENSE THIRD_PARTY_NOTICES.md README.md DESTINATION share/doc/mira)
install(DIRECTORY docs/ DESTINATION share/doc/mira/docs)
install(DIRECTORY licenses/ DESTINATION share/licenses/mira)
install(FILES third_party/m3shapes/LICENSE DESTINATION share/licenses/mira RENAME M3Shapes-Apache-2.0.txt)
set(CPACK_PACKAGE_NAME "mira")
set(CPACK_PACKAGE_VENDOR "Mira contributors")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Independent Material music companion")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${APP_NAME})
set(CPACK_PACKAGE_EXECUTABLES "mira;${APP_NAME}")
if(WIN32)
  set(CPACK_GENERATOR NSIS)
  set(CPACK_NSIS_DISPLAY_NAME ${APP_NAME})
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\mira.exe")
elseif(APPLE)
  set(CPACK_GENERATOR DragNDrop)
  set(CPACK_DMG_VOLUME_NAME ${APP_NAME})
else()
  set(CPACK_GENERATOR RPM)
  set(CPACK_PACKAGING_INSTALL_PREFIX /usr)
  set(CPACK_RPM_PACKAGE_LICENSE "MIT AND Apache-2.0")
  # Installing Mira replaces packages released under the old name.
  set(CPACK_RPM_PACKAGE_OBSOLETES "luwte")
  set(CPACK_RPM_PACKAGE_GROUP "Applications/Multimedia")
  set(CPACK_RPM_PACKAGE_REQUIRES "qt6-qtbase >= 6.8, qt6-qtbase-gui >= 6.8, qt6-qtdeclarative >= 6.8, qt6-qtwebengine >= 6.8, qt6-qtwebchannel >= 6.8, libsecret")
  set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION /usr/share/applications /usr/share/licenses /usr/share/icons /usr/share/icons/hicolor /usr/share/icons/hicolor/scalable /usr/share/icons/hicolor/scalable/apps /usr/share/metainfo)
endif()
include(CPack)
